### ISSUE TITLE
JDK Version of Binary Release at Maven Central

### ISSUE THREAD

**Issue by bergerbd** [Jsondb/jsondb-core#29]
Currently, I'm trying to use JsonDB in a project of mine that is targeting JDK 8. Unfortunately, the binary release at Maven Central is built with JDK 11. If I use it in a JRE 8 environment I end up with the following exception:

`Exception in thread "main" java.lang.UnsupportedClassVersionError: io/jsondb/JsonDBTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at TestMain.main(TestMain.java:7)`

As far as I see, JsonDB is built using JDK 8 according to .travis.yml. I would be glad, if you can use JDK 8 for feature releases, as well. It would help me with using your project without having to build it on my own with an older JDK.

**Comment by FarooqKhan** [comment]
@bergerbd yes travis uses jdk8, but i build the jars and push to maven central, and last time i did that i made mistake of using jdk11. I will use jdk8 and try to release a version soon.

I think having it build with jdk8 would be okay for everyone.

**Comment by simonecattaneo91** [comment]
Hi @FarooqKhan did you have any news on this? I've the exact same problem, I'm working on a project that use JDK 8 and I need the newer version to support the LocalDateTime properties.

**Comment by FarooqKhan** [comment]
I just released 2 new version on maven, Version 1.0.115-j8 and 1.0.115-j11, first is built using JDK8 and the second one is built using JDK 11.

for some reason maven always takes a few days before these versions are visible to everyone.
